---
title: "Modulo2"
output: github_document
date: "2023-07-09"
always_allow_html: true
---

```{r library, include=FALSE}
library(xlsx)
library(ggplot2)
library(lubridate)
library(dplyr)
library(reshape2)
library(dygraphs)
library(plotly)
```


```{r loading, include=FALSE}
base <- read.xlsx("D:\\Ciencia de datos\\Modulo 2\\Base_modulo2.xlsx",
                  sheetName = "Hoja1", as.data.frame = TRUE)
```

## 1st Exercise

Plot

```{r first, echo=FALSE}
base1 <- base %>%
  mutate(anio=year(Periodo),
         mes=month(Periodo)) %>%
  select(anio, mes, Export)
ggplot(base1, aes(factor(anio),Export))+
  geom_boxplot()+
  ggtitle("Exportaciones por anio \n(En millones de dolares)")+
  theme(plot.title = element_text(size = 16, colour = "blue",vjust = 2,
                                  hjust = 0.5))+
  labs(x="Anio",y="Exportaciones")
```

## 2nd Exercise

Plot

```{r second, echo=FALSE}
base3 <- base %>%
  mutate(anio=year(Periodo),
         mes=month(Periodo)) %>%
  select(anio, mes, Depositos, Creditos)

base_agrup <- melt(base3, id.vars = c("anio","mes"))

ggplot(base_agrup, aes(factor(anio), value, fill = variable))+
  geom_bar(stat="identity", position = "dodge")+
  labs(title = "Evolucion de depositos y cartera",
       subtitle = "(En millones de dolares)",
       x= "Anio",
       y= "Mill $us")+
  theme(axis.text.x = element_text(angle=90))
```


## 3rd Exercise

Plot

```{r third, echo=FALSE, message=FALSE}
base4 <- base %>%
  select(Periodo, IGAE, IPC)
base_agrup1 <- melt(base4, id.vars = "Periodo")
ggplot(base_agrup1, aes(Periodo, value))+
  geom_line()+facet_wrap(.~variable, scales = "free")+
  geom_smooth(method = "lm")

```

## 4th Exercise

Plot

```{r fourth, echo=FALSE}
base2 <- base %>%
  select(Depositos, Creditos)
base2ts <- ts(base2, start = c(2008,1), frequency = 12)
dygraph(base2ts) %>% dyRangeSelector()
```


## 5th Exercise

Plot

```{r fifth, echo=FALSE, message=FALSE, comment="", warning=FALSE}
baseplotly <- base %>%
  select(Periodo, Export)

fig <- plot_ly(baseplotly, type = 'scatter', mode = 'lines')%>%
  add_trace(x = ~Periodo, y = ~Export)%>%
  layout(showlegend = F, title='Time Series with Rangeslider',
         xaxis = list(rangeslider = list(visible = T)))
fig <- fig %>%
  layout(
    xaxis = list(zerolinecolor = '#ffff',
                 zerolinewidth = 2,
                 gridcolor = 'ffff'),
    yaxis = list(zerolinecolor = '#ffff',
                 zerolinewidth = 2,
                 gridcolor = 'ffff'),
    plot_bgcolor='#e5ecf6', width = 900)


fig
```

